### ISSUE TITLE
HPA created by HPATrait cannot get metrics of the pod referring to ContainerizedWorkload

### ISSUE THREAD

**Issue by captainroy-hy** [captainroy-hy/hpatrait#1]
![2e0743fe-fc11-47a8-8d2e-e9a228afeabc-401453](https://user-images.githubusercontent.com/5107364/84387325-ccefe100-ac2d-11ea-92bc-8d146dd3cba4.jpg)

As shown in the graph, even though the hpa is already created by the hpatrait but it cannot work as expected because of missing metrics. I created another hpatrait `sample-manual-hpatrait` manually , and the derived hpa can work well. 

![73eafcd2-7a34-44ed-830e-fcf1c381acd5-401453](https://user-images.githubusercontent.com/5107364/84387840-96ff2c80-ac2e-11ea-92f4-16d5124a4a43.jpg)
`kubectl top pods` shows that metrics-server is running well.

**Comment by captainroy-hy** [comment]
Reproducing steps are the same as indications in [README.md](https://github.com/captainroy-hy/hpatrait/blob/master/README.md). 
Additionally, what I mean "manually created" HPATrait is, apply a HPATrait with specified wrokloadRef through kubectl but not AppConfig. Then it can skip AppConfig controller and being reconciled by HPATrait controller directly.
```yaml
spec:
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 5
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
    uid: 28b5cffa-b521-4632-8524-aec489584009
```
